---
## Choose a build environment
dist: xenial
language: python

## Caching so the next build will be fast too.
cache: pip

python:
  ## test it on MULTIPLE different Python versions
  - "2.7" 

before_install:
  - echo "before_install"
  - pip install --upgrade pip
  - sudo apt-get update -qq
  
install:
  - echo "install start"
  
  ## FROM HERE
  - pip install flake8 mock nose

  ## get the reporter for Coveralls
  - pip install coveralls
  - pip install codecov

  ## TO HERE
  - echo "install done"
  
before_script:
  - echo "before script"
  - sleep 3
  
script:
  - echo "script start"
  - "python test.py"
  
after_script:
  - echo "after_script start"


