--- 
language: python
python: 
  - "2.7"
before_install:
  - echo "before_install"
install:
  - echo "install start"
   - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - echo "install done"
before_script:
  - echo "before script"
  - sleep 3
script:
  - echo "script start"
  - "python test.py"
  - pytest test.py
after_script:
  - echo "after_script start"
after_success:
  - coveralls





